/**
 * Career intelligence: what the user's evidence actually supports.
 *
 * This module is the product's most dangerous surface, because everything it emits is an
 * inference about somebody's career rather than a number they produced. Three rules keep it
 * honest, and each one is enforced by a test rather than by good intentions:
 *
 * 1. **Baseline analyses only.** Tailoring exists to raise a score. Feeding tailored scores
 *    back into the profile makes the system grade its own homework: it would report the user
 *    as strongest in whichever direction it most recently helped them rewrite. A user whose
 *    natural evidence supports Data Scientist at 0.81 and whose tailored resume hits 0.94
 *    has a profile built on 0.81.
 *
 * 2. **Median, not mean.** One unusual posting, written in the user's exact vocabulary or
 *    wildly mismatched, must not redefine a direction built from eighteen others.
 *
 * 3. **Say when there is not enough.** "Still learning your profile" is a real answer.
 *    Confidence is reported only where the sample supports it, and an insight nobody has
 *    the evidence for is not emitted at all.
 *
 * Pure functions over data the caller already holds. No model call, no network, because an
 * inference this consequential should be inspectable, and a sentence generated by a language
 * model about someone's career prospects is not.
 */

/** Enough analyses of one role before its median means anything. Below this it is anecdote. */
const MIN_FOR_MEDIUM_CONFIDENCE = 3;
const MIN_FOR_HIGH_CONFIDENCE = 8;
/** Enough total evidence before the product says anything about a career at all. */
const MIN_FOR_INSIGHTS = 4;

export interface BaselineAnalysis {
  /** The role the posting was for. Null when it was scored outside an application. */
  roleTitle: string | null;
  /** 0 to 1. Null for engines that do not score. */
  score: number | null;
  calibrated: boolean;
  /** False for an analysis of an already-tailored resume. Those never reach this module. */
  isBaseline: boolean;
  createdAt: string;
  missingRequirements: string[];
  coveredRequirements: string[];
}

export type Confidence = "low" | "medium" | "high";

export interface RoleAffinity {
  role: string;
  /** Median baseline score, 0 to 1. */
  affinity: number;
  confidence: Confidence;
  /** How many baseline analyses back it. Shown, because "86%" from one is not "86%". */
  sampleSize: number;
  calibratedOnly: boolean;
}

function key(role: string): string {
  return role.trim().toLowerCase();
}

/** Lower middle value for an even count, a real observation rather than a midpoint
 *  between two, which is a score no analysis produced. */
function median(values: number[]): number {
  const sorted = [...values].sort((a, b) => a - b);
  return sorted[Math.floor((sorted.length - 1) / 2)];
}

function confidenceFor(sampleSize: number): Confidence {
  if (sampleSize >= MIN_FOR_HIGH_CONFIDENCE) return "high";
  if (sampleSize >= MIN_FOR_MEDIUM_CONFIDENCE) return "medium";
  return "low";
}

/**
 * Median baseline affinity per role, strongest first.
 *
 * Analyses with no score are dropped rather than counted as zero: the keyword and base
 * engines deliberately produce none, and treating "did not measure" as "measured badly"
 * would drag every role the user ran those engines against toward the floor.
 */
export function roleAffinities(analyses: BaselineAnalysis[]): RoleAffinity[] {
  const groups = new Map<string, { label: string; scores: number[]; calibrated: boolean[] }>();

  for (const analysis of analyses) {
    if (!analysis.isBaseline) continue;
    if (!analysis.roleTitle?.trim()) continue;
    if (analysis.score === null) continue;

    const id = key(analysis.roleTitle);
    const group = groups.get(id) ?? {
      label: analysis.roleTitle.trim(),
      scores: [],
      calibrated: [],
    };
    group.scores.push(analysis.score);
    group.calibrated.push(analysis.calibrated);
    groups.set(id, group);
  }

  return [...groups.values()]
    .map((group) => ({
      role: group.label,
      affinity: median(group.scores),
      confidence: confidenceFor(group.scores.length),
      sampleSize: group.scores.length,
      calibratedOnly: group.calibrated.every(Boolean),
    }))
    .sort((a, b) => b.affinity - a.affinity);
}

// ---------------------------------------------------------------------------
// Adjacency
// ---------------------------------------------------------------------------

export const ADJACENCY_CATEGORIES = ["technical", "cross-functional", "non-technical"] as const;
export type AdjacencyCategory = (typeof ADJACENCY_CATEGORIES)[number];

export interface AdjacentRole {
  role: string;
  category: AdjacencyCategory;
  /** Why this is adjacent, in the user's own evidence. §77: never a bare suggestion. */
  rationale: string;
  transferable: string[];
  gaps: string[];
}

/**
 * The adjacency map.
 *
 * Hand-written, and that is the point. §77 requires every recommendation to be explainable
 * in terms of transferable evidence, which means the reasons have to exist before the
 * suggestion does. A similarity model over job titles would produce plausible lists with no
 * defensible answer to "why am I being shown this".
 *
 * A role with no entry gets no suggestions. Offering Product Manager to a marine biologist
 * because the map has no better idea is worse than an honest empty state.
 *
 * Non-technical entries are the ones to be most careful with: they are listed only where the
 * transferable evidence is genuinely load-bearing, never because the title sounds nearby.
 */
const ADJACENCY: Record<string, AdjacentRole[]> = {
  "software engineer": [
    {
      role: "Frontend Engineer",
      category: "technical",
      rationale: "Shares the same core engineering practice, narrowed to the interface layer.",
      transferable: ["Programming fundamentals", "Code review", "Testing", "Version control"],
      gaps: ["Browser rendering depth", "Design-system ownership", "Accessibility practice"],
    },
    {
      role: "Backend Engineer",
      category: "technical",
      rationale: "Shares the same core practice, narrowed to services and data.",
      transferable: ["Programming fundamentals", "API design", "Testing", "Debugging"],
      gaps: ["Distributed systems at scale", "Database tuning", "Operational on-call"],
    },
    {
      role: "Cloud Engineer",
      category: "technical",
      rationale: "Builds on deployment and infrastructure exposure most engineers accumulate.",
      transferable: ["Deployment pipelines", "Networking basics", "Scripting"],
      gaps: ["Infrastructure as code", "Cost management", "Multi-region architecture"],
    },
    {
      role: "DevOps Engineer",
      category: "technical",
      rationale: "Extends build-and-release work into owning the pipeline itself.",
      transferable: ["CI/CD familiarity", "Containers", "Automation scripting"],
      gaps: ["Observability tooling", "Incident response", "Platform reliability targets"],
    },
    {
      role: "Solutions Engineer",
      category: "cross-functional",
      rationale:
        "Technical depth plus the explaining-it-to-others half of the job, pointed at customers.",
      transferable: ["Technical communication", "Architecture", "Demonstrations", "Integration work"],
      gaps: ["Commercial discovery", "Objection handling", "Pre-sales process"],
    },
    {
      role: "Technical Product Manager",
      category: "cross-functional",
      rationale:
        "Translating requirements into implementation is already most of the job; the missing half is owning what gets built.",
      transferable: ["Technical fluency", "Cross-functional delivery", "Stakeholder communication"],
      gaps: ["Roadmap ownership", "Customer discovery", "Prioritisation frameworks", "Product analytics"],
    },
    {
      role: "Developer Advocate",
      category: "cross-functional",
      rationale: "Building with a tool and explaining it publicly draw on the same understanding.",
      transferable: ["Technical writing", "Example building", "Community answering"],
      gaps: ["Public speaking", "Content cadence", "Audience growth"],
    },
    {
      role: "Product Manager",
      category: "non-technical",
      rationale:
        "Only where there is evidence of shaping what gets built, not merely building it. Feature delivery with stakeholders is the transferable part.",
      transferable: ["Requirements translation", "Stakeholder management", "Delivery judgement"],
      gaps: ["Market and user research", "Commercial framing", "Metrics ownership", "Roadmap tradeoffs"],
    },
    {
      role: "Implementation Consultant",
      category: "non-technical",
      rationale: "Configuring and integrating software for a customer, rather than authoring it.",
      transferable: ["Integration work", "Troubleshooting", "Client-facing explanation"],
      gaps: ["Project scoping", "Change management", "Commercial scoping"],
    },
  ],
  "data scientist": [
    {
      role: "Machine Learning Engineer",
      category: "technical",
      rationale: "Same modelling foundation, weighted toward putting models into production.",
      transferable: ["Modelling", "Python", "Feature engineering", "Evaluation design"],
      gaps: ["MLOps", "Serving infrastructure", "Model monitoring", "Containerisation"],
    },
    {
      role: "Analytics Engineer",
      category: "technical",
      rationale: "Shares the SQL and data-modelling core, aimed at trustworthy datasets.",
      transferable: ["SQL", "Data modelling", "Warehouse familiarity", "Stakeholder reporting"],
      gaps: ["Transformation tooling", "Data testing", "Pipeline orchestration"],
    },
    {
      role: "Data Engineer",
      category: "technical",
      rationale: "Builds the pipelines that analysis already depends on.",
      transferable: ["SQL", "Python", "Data quality judgement"],
      gaps: ["Distributed processing", "Orchestration at scale", "Streaming"],
    },
    {
      role: "Product Analyst",
      category: "cross-functional",
      rationale: "Analysis pointed at product decisions rather than at models.",
      transferable: ["Analysis", "Experiment design", "Communicating findings"],
      gaps: ["Product metric frameworks", "Roadmap influence"],
    },
    {
      role: "Technical Product Manager",
      category: "cross-functional",
      rationale: "Quantitative judgement and stakeholder work, applied to what gets built.",
      transferable: ["Data-informed decisions", "Stakeholder communication", "Technical fluency"],
      gaps: ["Roadmap ownership", "Customer discovery", "Prioritisation frameworks"],
    },
    {
      role: "Data Product Manager",
      category: "non-technical",
      rationale: "Owning data products, where knowing what the data can honestly support matters.",
      transferable: ["Data literacy", "Requirements framing", "Cross-team communication"],
      gaps: ["Product strategy", "Commercial framing", "Roadmap tradeoffs"],
    },
  ],
};

/** Aliases, so a posting titled "Sr. Software Engineer" finds the same map entry. */
const ALIASES: Record<string, string> = {
  "senior software engineer": "software engineer",
  "sr software engineer": "software engineer",
  "sr. software engineer": "software engineer",
  "full-stack engineer": "software engineer",
  "full stack engineer": "software engineer",
  "backend engineer": "software engineer",
  "frontend engineer": "software engineer",
  "software developer": "software engineer",
  "senior data scientist": "data scientist",
  "sr data scientist": "data scientist",
  "machine learning engineer": "data scientist",
  "ml engineer": "data scientist",
};

/**
 * Roles adjacent to a primary one, with the reasoning attached.
 *
 * Filters out the primary role itself, since an alias means "Frontend Engineer" maps through
 * Software Engineer, and suggesting Frontend Engineer back to a frontend engineer is noise.
 */
export function adjacentRoles(primary: string | null): AdjacentRole[] {
  if (!primary?.trim()) return [];

  const id = key(primary);
  const mapped = ADJACENCY[id] ?? ADJACENCY[ALIASES[id] ?? ""] ?? [];

  return mapped.filter((role) => key(role.role) !== id);
}

// ---------------------------------------------------------------------------
// Insights
// ---------------------------------------------------------------------------

export type InsightKind = "strength" | "gap" | "adjacency" | "pattern";

export interface Insight {
  kind: InsightKind;
  label: string;
  body: string;
}

export interface CareerInsights {
  /** False when there is not enough evidence. The UI says so instead of inventing one. */
  sufficient: boolean;
  items: Insight[];
  analysed: number;
}

/** The n most common entries in a list of requirement strings. */
function mostCommon(values: string[], limit: number): string[] {
  const counts = new Map<string, { label: string; n: number }>();
  for (const value of values) {
    const id = value.trim().toLowerCase();
    if (!id) continue;
    const entry = counts.get(id) ?? { label: value.trim(), n: 0 };
    entry.n += 1;
    counts.set(id, entry);
  }
  return [...counts.values()]
    .sort((a, b) => b.n - a.n)
    .slice(0, limit)
    .map((entry) => entry.label);
}

/**
 * Observable patterns across the user's baseline evidence.
 *
 * Every item is a claim about data in hand, phrased as an observation rather than advice.
 * There is deliberately no encouragement, no exclamation, and no forecast: this component
 * replaced a composite "pulse" score precisely because a number with no interpretation is
 * less useful than a sentence with a source.
 *
 * `declaredInterest` is what the user says they are aiming at. §76: the useful insight is
 * the GAP between that and the evidence, and the product never silently retargets them.
 */
export function careerInsights(
  analyses: BaselineAnalysis[],
  applications: { status: string; role: string }[],
  declaredInterest?: string | null,
): CareerInsights {
  const baseline = analyses.filter((analysis) => analysis.isBaseline);
  const affinities = roleAffinities(baseline);

  if (baseline.length < MIN_FOR_INSIGHTS || affinities.length === 0) {
    return { sufficient: false, items: [], analysed: baseline.length };
  }

  const items: Insight[] = [];
  const strongest = affinities[0];

  items.push({
    kind: "strength",
    label: "Strongest alignment",
    body: `Across ${strongest.sampleSize} baseline ${
      strongest.sampleSize === 1 ? "analysis" : "analyses"
    }, your resume aligns most consistently with ${strongest.role} roles (median ${Math.round(
      strongest.affinity * 100,
    )} out of 100).`,
  });

  // §76: what they want vs what the evidence supports. Stated, never acted on.
  if (declaredInterest?.trim()) {
    const declared = affinities.find((a) => key(a.role) === key(declaredInterest));
    if (declared && key(declared.role) !== key(strongest.role)) {
      items.push({
        kind: "pattern",
        label: "Target versus evidence",
        body: `You are targeting ${declaredInterest.trim()}, but your baseline analyses currently show stronger alignment with ${strongest.role}. That is a gap in the evidence, not a verdict on the goal. It points at what the resume would need to show.`,
      });
    }
  }

  const recurringGaps = mostCommon(
    baseline.flatMap((analysis) => analysis.missingRequirements),
    3,
  );
  if (recurringGaps.length > 0) {
    items.push({
      kind: "gap",
      label: "Recurring gap",
      body: `${recurringGaps.join(", ")} ${
        recurringGaps.length === 1 ? "is" : "are"
      } missing most often across the postings you have analysed. Recurring gaps cost more than one-off ones.`,
    });
  }

  const recurringStrengths = mostCommon(
    baseline.flatMap((analysis) => analysis.coveredRequirements),
    3,
  );
  if (recurringStrengths.length > 0) {
    items.push({
      kind: "strength",
      label: "Consistent evidence",
      body: `${recurringStrengths.join(", ")} ${
        recurringStrengths.length === 1 ? "is" : "are"
      } covered most reliably across those same postings.`,
    });
  }

  const adjacency = adjacentRoles(strongest.role);
  if (adjacency.length > 0) {
    const crossFunctional = adjacency.find((role) => role.category === "cross-functional");
    if (crossFunctional) {
      items.push({
        kind: "adjacency",
        label: "Adjacent direction",
        body: `${crossFunctional.role} is reachable from this evidence: ${crossFunctional.rationale.toLowerCase()}`,
      });
    }
  }

  // A pattern across applications, only when there is enough of a spread to be a pattern.
  if (applications.length >= MIN_FOR_INSIGHTS) {
    const closed = applications.filter(
      (application) => application.status === "rejected" || application.status === "withdrawn",
    ).length;
    const live = applications.length - closed;
    if (live > 0 && closed > 0) {
      items.push({
        kind: "pattern",
        label: "Pipeline",
        body: `${live} of ${applications.length} tracked applications are still open. Volume is only useful next to what it converts into, and the pipeline chart shows where they sit.`,
      });
    }
  }

  return { sufficient: true, items, analysed: baseline.length };
}
