"use client";

/**
 * Career Intelligence: patterns across the user's evolving profile.
 *
 * This replaced a composite "Job Hunt Pulse" score. A single number with no defined
 * interpretation is worse than a sentence with a source: nobody can say what a pulse of 72
 * means, whereas "Kubernetes is missing from most postings you analysed" is checkable.
 *
 * Everything shown is generated by `careerInsights` from BASELINE analyses, and every claim
 * is about data in hand. There is deliberately no encouragement, no forecast and no
 * exclamation mark, because the failure mode for this panel is AI-slop optimism, and the guard
 * against it is that the generator can only phrase observations it has evidence for.
 *
 * When there is not enough evidence it says so. §69: do not fabricate an insight to avoid
 * an empty card.
 */

import Link from "next/link";

import type { CareerInsights as Insights, InsightKind } from "@/lib/career";

const TONES: Record<InsightKind, string> = {
  strength: "good",
  gap: "gap",
  adjacency: "adjacent",
  pattern: "neutral",
};

export function CareerIntelligence({ insights }: { insights: Insights }) {
  return (
    <section className="obsidian-panel dash-panel dash-panel--intelligence">
      <header className="dash-panel__head">
        <div>
          <h2 className="panel-title">Career Intelligence</h2>
          <p className="dash-panel__sub">Patterns across your baseline analyses</p>
        </div>
      </header>

      {!insights.sufficient ? (
        <div className="dash-panel__empty-block">
          <p>More data will unlock deeper insights.</p>
          <p>
            {insights.analysed === 0
              ? "Nothing has been analysed yet."
              : `${insights.analysed} baseline ${
                  insights.analysed === 1 ? "analysis" : "analyses"
                } so far.`}{" "}
            Patterns worth stating need several, since a claim drawn from one or two postings
            would look exactly as confident as one drawn from twenty, and mean far less.
          </p>
          <Link href="/matcher" className="button button--ghost">
            Analyse a role
          </Link>
        </div>
      ) : (
        <>
          <ul className="insight-list">
            {insights.items.map((insight) => (
              <li key={insight.label} data-tone={TONES[insight.kind]}>
                <span className="insight-list__label">{insight.label}</span>
                <p>{insight.body}</p>
              </li>
            ))}
          </ul>

          {/*
            The provenance line. It is the difference between an insight and an assertion,
            and it is also the reminder that tailored rewrites are excluded on purpose.
          */}
          <p className="dash-panel__note">
            Derived from {insights.analysed} baseline{" "}
            {insights.analysed === 1 ? "analysis" : "analyses"}, original résumés only.
            Tailored versions are excluded so a rewrite cannot reshape your profile.
          </p>
        </>
      )}
    </section>
  );
}
