import { ENGINE_META, type ScoreResult } from "@/lib/types";

/**
 * Prose and suggested bullets from a language-model engine (SPEC §5.1 item 5).
 *
 * Rendered only when a language model actually produced it, and labelled with which model
 * that was. The distinction matters: everything else on the results page comes from a
 * measured, evaluated model, and this comes from a general-purpose one with no evaluation
 * behind it on this task. Presenting the two in the same voice would lend the second the
 * first's credibility.
 */
export function WrittenFeedback({ result }: { result: ScoreResult }) {
  const hasProse = result.summary || (result.suggestedBullets?.length ?? 0) > 0;
  if (!hasProse) return null;

  const meta = ENGINE_META[result.engine];

  return (
    <section
      aria-labelledby="feedback-heading"
      className="result-panel"
    >
      <h2
        id="feedback-heading"
        className="panel-title"
      >
        Written feedback
      </h2>

      <p className="mt-1 text-xs text-slate-500 dark:text-slate-400">
        Generated by {meta.name} (
        <span className="font-mono">{result.modelId}</span>). This is a general-purpose
        language model writing about your resume, and it has no evaluation behind it on this
        task, unlike the score above. Read it as a second opinion, not a measurement.
      </p>

      {result.summary && (
        <p className="mt-4 leading-relaxed text-slate-700 dark:text-slate-300">{result.summary}</p>
      )}

      {result.suggestedBullets && result.suggestedBullets.length > 0 && (
        <>
          <h3 className="mt-5 panel-title">
            Suggested rewrites
          </h3>
          <ul className="mt-2 space-y-2">
            {result.suggestedBullets.map((bullet, index) => (
              <li
                key={index}
                className="border-l-2 border-slate-200 pl-3 text-sm leading-relaxed text-slate-700 dark:border-slate-700 dark:text-slate-300"
              >
                {bullet}
              </li>
            ))}
          </ul>
          <p className="mt-3 text-xs text-slate-500 dark:text-slate-400">
            These are reframings of experience already on your resume. Check each one against
            what you actually did before using it, because you have to be able to say it in an
            interview.
          </p>
        </>
      )}
    </section>
  );
}
